version: 2

references:
  container_config: &container_config
    docker:
      - image: circleci/node:9.10
    environment:
      TZ: "/usr/share/zoneinfo/America/Los_Angeles"

  workspace_root: &workspace_root
    /tmp/workspace

  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

  restore_node_modules: &restore_node_modules
    run:
      name: Restore dependencies from workspace
      command: |
        mv /tmp/workspace/node_modules .

  modules_cache_key: &modules_cache_key
    key: v1-cache-{{ checksum "yarn.lock" }}

jobs:
  dependencies:
    <<: *container_config
    steps:
      - checkout
      - *attach_workspace
      - restore_cache:
          <<: *modules_cache_key
      - run:
          name: Install dependencies
          command: |
            if [ ! -d node_modules ]; then
              yarn bootstrap
            fi
      - save_cache:
          <<: *modules_cache_key
          paths:
            - node_modules
      - run:
          name: Move dependencies to workspace
          command: mv node_modules /tmp/workspace/
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - node_modules

  build_and_test:
    <<: *container_config
    steps:
      - checkout
      - *attach_workspace
      - *restore_node_modules
      - run:
          name: Build
          command: |
            yarn build
      - run:
          name: Create timestamp file
          command: |
            echo "$(date +%Y%m)" > _timestamp_file
      - restore_cache:
          key: v1-reporter-{{ checksum "_timestamp_file" }}
      - run:
          name: Setup Code Climate test-reporter
          command: |
            if [ ! -f cc-test-reporter ]; then
              curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
              chmod +x ./cc-test-reporter
            fi
      - save_cache:
          key: v1-reporter-{{ checksum "_timestamp_file" }}
          paths:
            - cc-test-reporter
      - run:
          name: Run tests
          command: |
            yarn test
      - run:
          name: Upload Coverage
          command: |
            for f in packages/*; do
              if [ -f $f/coverage/lcov.info ]; then
                echo $f;
                ./cc-test-reporter format-coverage -t lcov -o coverage/coverage.${f//\//-}.json $f/coverage/lcov.info;
              fi
            done;
            ./cc-test-reporter sum-coverage -o coverage/coverage.total.json coverage/coverage.*.json;
            ./cc-test-reporter upload-coverage -i coverage/coverage.total.json;

  lint:
    <<: *container_config
    steps:
      - checkout
      - *attach_workspace
      - *restore_node_modules
      - run:
          name: Lint
          command: yarn lint

workflows:
  version: 2
  build_and_test:
    jobs:
      - dependencies
      - build_and_test:
          requires:
            - dependencies
      - lint:
          requires:
            - dependencies
